#!/bin/bash


for i in {301..314}; do wget http://www.cs.utexas.edu/~geocklam/CS331/assignment3/input$i.txt; done
for i in {301..314}; do wget http://www.cs.utexas.edu/~geocklam/CS331/assignment3/output$i.txt; done


echo "Testing in progress... do not disturb... " 

for i in {301..314}; do time ./run input$i.txt myOutput$i.txt; echo $i; java verify input$.txt myOutput$i.txt output$i.txt; rm myOutput$i;done

echo "============================="
echo "Finish"