#!/bin/bash

echo "Testing in progress... do not disturb... " 
javac *.java

for i in {301..314}; do time ./run input$i.txt myOutput$i.txt; echo $i; java verify input$i.txt myOutput$i.txt output$i.txt ;done

echo "============================="
echo "Finish"
